### ISSUE TITLE
Feature Request for elegant way to access parameter default values

### ISSUE THREAD

**Issue by StenCalDabran** [GregOnNet/kentan-schematics#6]
When using models, sometimes it is necessary to compare some value with the default value, e.g. in a test that should ensure that data was not changed in case of an error. Therefore it would be nice to have a better way to access the default values than to take the whole model.
The current way:
`Kentan.sketch(ForExampleSketch).model().exampleValueLevel1.exampleValueLevel2`
Maybe there is be a prettier way to do this with some kind of get method.

**Comment by GregOnNet** [comment]
Thank you for the request.
It definitely makes life easier having the possibility to _get_ default values providing some kind of query.

In  [version 1.2](https://github.com/GregOnNet/kentan/releases/tag/v1.2.0) you will find a new method called `get`.

If you have further ideas please file a feature request directly in the [Kentan](https://github.com/GregOnNet/kentan/issues) repository.
This repository here is just for the tooling. :-)
